In [1]:
import numpy as np

In [3]:
arr = np.array(82)
print(arr)

82


In [4]:
l1 = np.array([1,2])
print(l1)

[1 2]


In [5]:
l2 = np.array([[1,2],[3,4]])
print(l2)

[[1 2]
 [3 4]]


In [6]:
l3 = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(l3)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [7]:
for i in range(1,5):
 ln = np.array([1,2,3,4],ndmin=i)
 print(ln)
 print(ln.ndim)


[1 2 3 4]
1
[[1 2 3 4]]
2
[[[1 2 3 4]]]
3
[[[[1 2 3 4]]]]
4


In [8]:
print("methods")
arr =np.arange(2,7,3)
print(arr)

methods
[2 5]


In [9]:
arr1= np.zeros((7,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr2= arr1.T
print(arr2)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [11]:
arr3= np.ones((2,5))
print(arr3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
arr5 = np.full((2,6),7)
print(arr5)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [13]:
arr4 = np.full((3,6),"anits",dtype=str)
print(arr4)

[['a' 'a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a' 'a' 'a']]


In [14]:
arr6 = np.full((3,6),"anits",dtype='U2')
print(arr6)

[['an' 'an' 'an' 'an' 'an' 'an']
 ['an' 'an' 'an' 'an' 'an' 'an']
 ['an' 'an' 'an' 'an' 'an' 'an']]


In [15]:
arr7 = np.full((3,6),"anits",dtype=object)
print(arr7)

[['anits' 'anits' 'anits' 'anits' 'anits' 'anits']
 ['anits' 'anits' 'anits' 'anits' 'anits' 'anits']
 ['anits' 'anits' 'anits' 'anits' 'anits' 'anits']]


In [16]:
arr8 = np.arange(9)
print(arr8)

[0 1 2 3 4 5 6 7 8]


In [17]:
arr9 = np.eye(5,8,3)
print(arr9)

[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [18]:
arr10 = np.identity(3)
print(arr10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
arr11 = np.linspace(0,20,5)
print(arr11)

[ 0.  5. 10. 15. 20.]


In [23]:
import pandas as pd

In [24]:
data = pd.DataFrame({
 'Height': [165,172,158,185,170],
 'Weight': [65.2,68.5,61.9,78.2,70.7]
})
print("ratio")
print(data)

ratio
   Height  Weight
0     165    65.2
1     172    68.5
2     158    61.9
3     185    78.2
4     170    70.7


In [26]:
import pandas as pd
data = pd.DataFrame({
 'EduLevel': ['High School', 'Bachelor','Master','PhD'],
 'Ranking': [5,1,2,4]
})
print("ordinal")
print(data)

ordinal
      EduLevel  Ranking
0  High School        5
1     Bachelor        1
2       Master        2
3          PhD        4


In [28]:
import pandas as pd
data = pd.DataFrame({
 'gender': ['M','F','F','M','M'],
 'age': [22,31,21,45,12]
})
print("nominal")
print(data)

nominal
  gender  age
0      M   22
1      F   31
2      F   21
3      M   45
4      M   12


In [29]:
import pandas as pd
data = pd.DataFrame({
 'Temperature': [23.5,26.5,30.1,28.2,25.4]
})
print("interval")
print(data)

interval
   Temperature
0         23.5
1         26.5
2         30.1
3         28.2
4         25.4


In [30]:
print("EXPERIMENT 2")

EXPERIMENT 2


In [31]:
import pandas as pd
import random
from datetime import datetime, timedelta

# Generate random sales data
random.seed(0)  # For reproducibility

dates = [datetime(2023, 1, 1) + timedelta(days=i) for i in range(10)]
products = ['Apple', 'Orange', 'Banana']
units_sold = [random.randint(50, 300) for _ in range(10)]
prices = {'Apple': 1.5, 'Orange': 2.0, 'Banana': 1.0}
price_per_unit = [prices[random.choice(products)] for _ in range(10)]
total_price = [units * price for units, price in zip(units_sold, price_per_unit)]

# Create a DataFrame
df = pd.DataFrame({
    'Date': dates,
    'Product': [random.choice(products) for _ in range(10)],
    'Units Sold': units_sold,
    'Price per Unit': price_per_unit,
    'Total Price': total_price
})

# Save the DataFrame to a CSV file
df.to_csv('sales_data_generated.csv', index=False)

print("Dataset saved as 'sales_data_generated.csv'")


Dataset saved as 'sales_data_generated.csv'


In [32]:
import os

csv_filename = 'sales_data_generated.csv'  # Adjust this to your actual filename

if os.path.exists(csv_filename):
    print(f"The CSV file '{csv_filename}' exists.")
else:
    print(f"The CSV file '{csv_filename}' does not exist.")


The CSV file 'sales_data_generated.csv' exists.


In [33]:
#loafing dataset

In [34]:

# Load the CSV file into a DataFrame
df = pd.read_csv('sales_data_generated.csv')

# Display the first few rows of the DataFrame
print(df.head())

         Date Product  Units Sold  Price per Unit  Total Price
0  2023-01-01   Apple         266             2.0        532.0
1  2023-01-02  Banana         148             2.0        296.0
2  2023-01-03  Orange         244             2.0        488.0
3  2023-01-04  Banana         277             2.0        554.0
4  2023-01-05  Banana         157             1.0        157.0


In [35]:
#basic operations

In [43]:
# Display first 5 rows
print(df.head())

         Date Product  Units Sold  Price per Unit  Total Price
0  2023-01-01   Apple         266             2.0        532.0
1  2023-01-02  Banana         148             2.0        296.0
2  2023-01-03  Orange         244             2.0        488.0
3  2023-01-04  Banana         277             2.0        554.0
4  2023-01-05  Banana         157             1.0        157.0


In [44]:
# Display last 5 rows
print(df.tail())

         Date Product  Units Sold  Price per Unit  Total Price
5  2023-01-06  Banana          60             1.5         90.0
6  2023-01-07   Apple         116             1.0        116.0
7  2023-01-08  Orange         297             1.5        445.5
8  2023-01-09   Apple         180             2.0        360.0
9  2023-01-10  Banana         174             1.5        261.0


In [45]:
# Check column names
print(df.columns)

Index(['Date', 'Product', 'Units Sold', 'Price per Unit', 'Total Price'], dtype='object')


In [46]:
# Check data types
print(df.dtypes)

Date               object
Product            object
Units Sold          int64
Price per Unit    float64
Total Price       float64
dtype: object


In [47]:
# Summary statistics
print(df.describe())

       Units Sold  Price per Unit  Total Price
count     10.0000       10.000000    10.000000
mean     191.9000        1.650000   329.950000
std       76.9263        0.411636   173.020944
min       60.0000        1.000000    90.000000
25%      150.2500        1.500000   183.000000
50%      177.0000        1.750000   328.000000
75%      260.5000        2.000000   477.375000
max      297.0000        2.000000   554.000000


In [49]:
#

In [50]:
# accessing specific col or row

In [51]:
# Selecting a single column
print(df['Date'])

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
5    2023-01-06
6    2023-01-07
7    2023-01-08
8    2023-01-09
9    2023-01-10
Name: Date, dtype: object


In [52]:
# Selecting multiple columns
print(df[['Date', 'Product', 'Units Sold']])

         Date Product  Units Sold
0  2023-01-01   Apple         266
1  2023-01-02  Banana         148
2  2023-01-03  Orange         244
3  2023-01-04  Banana         277
4  2023-01-05  Banana         157
5  2023-01-06  Banana          60
6  2023-01-07   Apple         116
7  2023-01-08  Orange         297
8  2023-01-09   Apple         180
9  2023-01-10  Banana         174


In [53]:
# Selecting rows by index
print(df.iloc[0])  # First row

Date              2023-01-01
Product                Apple
Units Sold               266
Price per Unit           2.0
Total Price            532.0
Name: 0, dtype: object


In [55]:
# Selecting rows by condition
print(df[df['Units Sold'] > 200])

         Date Product  Units Sold  Price per Unit  Total Price
0  2023-01-01   Apple         266             2.0        532.0
2  2023-01-03  Orange         244             2.0        488.0
3  2023-01-04  Banana         277             2.0        554.0
7  2023-01-08  Orange         297             1.5        445.5


In [56]:
#

In [57]:
# Data Manipulation

In [58]:
# Adding a new column 'Revenue'
df['Revenue'] = df['Units Sold'] * df['Price per Unit']

In [59]:
print(df.head())

         Date Product  Units Sold  Price per Unit  Total Price  Revenue
0  2023-01-01   Apple         266             2.0        532.0    532.0
1  2023-01-02  Banana         148             2.0        296.0    296.0
2  2023-01-03  Orange         244             2.0        488.0    488.0
3  2023-01-04  Banana         277             2.0        554.0    554.0
4  2023-01-05  Banana         157             1.0        157.0    157.0


In [61]:
# Modifying existing column 'Total Price'
df['Total Price'] = df['Units Sold'] * df['Price per Unit']
print(df.head())

         Date Product  Units Sold  Price per Unit  Total Price  Revenue
0  2023-01-01   Apple         266             2.0        532.0    532.0
1  2023-01-02  Banana         148             2.0        296.0    296.0
2  2023-01-03  Orange         244             2.0        488.0    488.0
3  2023-01-04  Banana         277             2.0        554.0    554.0
4  2023-01-05  Banana         157             1.0        157.0    157.0


In [62]:
# Grouping by 'Product' and calculating total sales
sales_per_product = df.groupby('Product')['Total Price'].sum()
print(sales_per_product)

Product
Apple     1008.0
Banana    1358.0
Orange     933.5
Name: Total Price, dtype: float64


In [63]:
#

In [64]:
# Data Analysis

In [65]:
# Sorting by 'Date' in ascending order
sorted_df = df.sort_values(by='Date')
print(sorted_df.head())


         Date Product  Units Sold  Price per Unit  Total Price  Revenue
0  2023-01-01   Apple         266             2.0        532.0    532.0
1  2023-01-02  Banana         148             2.0        296.0    296.0
2  2023-01-03  Orange         244             2.0        488.0    488.0
3  2023-01-04  Banana         277             2.0        554.0    554.0
4  2023-01-05  Banana         157             1.0        157.0    157.0


In [66]:
#

In [67]:
# Exporting Data

In [68]:
# Save the modified DataFrame back to CSV
df.to_csv('sales_data_modified.csv', index=False)
print("Modified data saved to 'sales_data_modified.csv'")


Modified data saved to 'sales_data_modified.csv'


In [70]:
print(df.head())

         Date Product  Units Sold  Price per Unit  Total Price  Revenue
0  2023-01-01   Apple         266             2.0        532.0    532.0
1  2023-01-02  Banana         148             2.0        296.0    296.0
2  2023-01-03  Orange         244             2.0        488.0    488.0
3  2023-01-04  Banana         277             2.0        554.0    554.0
4  2023-01-05  Banana         157             1.0        157.0    157.0
